In [4]:
import numpy as np
import pandas as pd
import seaborn as sns
import os

In [5]:
df = pd.read_csv("C:\\Users\\Sabrina\\Desktop\\OMDS Sp26 HW\\r_espresso Bean & Brew Database (Responses) - Form Responses 1.csv")
df

,Timestamp,Bean/blend name,Origin,Caffeine,Roast level,Roast date,Roaster,Roaster's city,Roaster's country,Product weight (grams),...,Shot time (seconds),Espresso machine,Grinder,Burr set,Grind setting,Water temperature (°C),Basket specs,Profile,Additional workflow/equipment,Reddit username
0,1/13/2025 13:31:15,Jairo Arcila Espresso,Colombia,Full caffeine,2.0,11/24/2024,Monogram,Calgary,Canada,300.0,...,30,ECM Synchronika,Monolith MAX Gen 1,Shuriken LM,1.75,93.8,E&B Lab Superfine,Pre-infusion 4 mL/s for 5 s ramp up to 8 mL/s ...,"RDT, WDT",NaN
1,1/13/2025 13:32:32,Milky Cake Filter,Colombia,Full caffeine,2.0,5/24/2023,DAK,Amsterdam,Netherlands,1000.0,...,30-35,ECM Synchronika,Monolith MAX Gen 1,Shuriken LM,NaN,94.4,E&B Lab Superfine,Pre-infusion 4 mL/s for 5 s ramp up to 8 mL/s ...,"RDT, WDT",NaN
2,1/14/2025 6:48:07,Bank Robber,Blend,Full caffeine,4.0,NaN,Cat & Cloud,Santa Cruz,United States,283.0,...,30,DeLonghi ECP 35.31,Baratza Encore ESP,NaN,17,NaN,NaN,NaN,NaN,awesomenessjared
3,1/14/2025 8:07:28,Eclipse,Blend,Full caffeine,5.0,NaN,Onyx,NaN,United States,283.0,...,25-35,La Marzocco Linea Micra,1zpresso J-Ultra,NaN,1.35,95.0,NaN,NaN,WDT,NaN
4,1/14/2025 8:11:08,Christmas in July,Blend,Full caffeine,4.0,NaN,Black & White,NaN,United States,340.0,...,25-35,La Marzocco Linea Micra,1Zpresso J-Ultra,NaN,1.25,95.0,NaN,NaN,WDT,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
215,4/19/2026 11:43:05,Gracenote Misty Valley Espresso,Ethiopia,Full caffeine,3.0,4/7/2026,Gracenote Coffee,Boston,United States,340.0,...,45,ECM Synchronika II,Zerno Z1,64 HU,130 nm,94.0,VST 18g Ridgeless,Ramp up to 6 bar using flow control paddle,"RDT, WDT, Puck screen",NaN
216,5/5/2026 6:22:51,Common Bond Espresso,Blend,Full caffeine,3.0,NaN,Ember and Bean Roasting Co,"Hudson, WI",United States,340.0,...,35,Breville Bambino Plus,Baratza Encore ESP,Stock burrs,NaN,NaN,NaN,Machine default,"RDT, WDT, Puck screen",NaN
217,5/7/2026 9:13:01,Yirgacheffe,Ethiopia,Full caffeine,3.0,NaN,Press Coffee,Phoenix,United States,340.0,...,30,Flair Pro 3,DF64,Titanium burrs,21.5,96.0,Stock,"Pre-infusion at <1bar until fully saturated, s...",WDT,gibson_
218,5/8/2026 15:20:07,Brazil Cemmorado,Brazil,Full caffeine,4.0,5/1/2026,Origins Roastery,Budva,Montenegro,1000.0,...,28-30,Sanremo You,Eureka Helios,Stock burrs,NaN,96.0,Stock,Flat 9 bar,NaN,u/WorkingPower4803
219,5/10/2026 10:45:53,companion blend,Colombia,Full caffeine,3.0,NaN,Little wolf,NaN,United States,NaN,...,33,Lelit liz,EM specialita,Stock burrs,NaN,95.0,20g IMS,10s 3bar 23 sec 8.5 bar,WDT,NaN

In [6]:
# Delete unnecessary columns

df = df.drop(columns=["Timestamp", "Bean/blend name", "Roast date", "Roaster's city", "Currency", "Price paid", "Cost per 100 g", "Cost per pound", "Product URL", "Reddit username"])
df

,Origin,Caffeine,Roast level,Roaster,Roaster's country,Product weight (grams),Tasting notes,Rating,Time rested (days),Dose (grams),...,Brew ratio,Shot time (seconds),Espresso machine,Grinder,Burr set,Grind setting,Water temperature (°C),Basket specs,Profile,Additional workflow/equipment
0,Colombia,Full caffeine,2.0,Monogram,Canada,300.0,Rum & brown sugar,9.0,7.0,18.0,...,1:2.5,30,ECM Synchronika,Monolith MAX Gen 1,Shuriken LM,1.75,93.8,E&B Lab Superfine,Pre-infusion 4 mL/s for 5 s ramp up to 8 mL/s ...,"RDT, WDT"
1,Colombia,Full caffeine,2.0,DAK,Netherlands,1000.0,"Cardamom, vanilla, nuts",10.0,5.0,18.0,...,1:2.5,30-35,ECM Synchronika,Monolith MAX Gen 1,Shuriken LM,NaN,94.4,E&B Lab Superfine,Pre-infusion 4 mL/s for 5 s ramp up to 8 mL/s ...,"RDT, WDT"
2,Blend,Full caffeine,4.0,Cat & Cloud,United States,283.0,"Smooth (sorry, my tasting notes are terrible)",8.0,5.0,16.3,...,1:2.0,30,DeLonghi ECP 35.31,Baratza Encore ESP,NaN,17,NaN,NaN,NaN,NaN
3,Blend,Full caffeine,5.0,Onyx,United States,283.0,"Chocolate, nuts, low acidity",7.0,5.0,18.0,...,1:2.0,25-35,La Marzocco Linea Micra,1zpresso J-Ultra,NaN,1.35,95.0,NaN,NaN,WDT
4,Blend,Full caffeine,4.0,Black & White,United States,340.0,"Funky, slightly acidic",3.0,14.0,18.0,...,1:2.5,25-35,La Marzocco Linea Micra,1Zpresso J-Ultra,NaN,1.25,95.0,NaN,NaN,WDT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
215,Ethiopia,Full caffeine,3.0,Gracenote Coffee,United States,340.0,"Blueberry cobbler/pie, chocolate",8.0,6.0,16.5,...,1:2.2,45,ECM Synchronika II,Zerno Z1,64 HU,130 nm,94.0,VST 18g Ridgeless,Ramp up to 6 bar using flow control paddle,"RDT, WDT, Puck screen"
216,Blend,Full caffeine,3.0,Ember and Bean Roasting Co,United States,340.0,NaN,8.0,NaN,19.0,...,1:2.4,35,Breville Bambino Plus,Baratza Encore ESP,Stock burrs,NaN,NaN,NaN,Machine default,"RDT, WDT, Puck screen"
217,Ethiopia,Full caffeine,3.0,Press Coffee,United States,340.0,NaN,8.0,NaN,18.0,...,1:2.0,30,Flair Pro 3,DF64,Titanium burrs,21.5,96.0,Stock,"Pre-infusion at <1bar until fully saturated, s...",WDT
218,Brazil,Full caffeine,4.0,Origins Roastery,Montenegro,1000.0,toffee,7.0,8.0,17.0,...,1:1.9,28-30,Sanremo You,Eureka Helios,Stock burrs,NaN,96.0,Stock,Flat 9 bar,NaN
219,Colombia,Full caffeine,3.0,Little wolf,United States,NaN,Chocolate cherry,9.0,NaN,20.0,...,1:1.6,33,Lelit liz,EM specialita,Stock burrs,NaN,95.0,20g IMS,10s 3bar 23 sec 8.5 bar,WDT

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 220 entries, 0 to 219
Data columns (total 21 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Origin                         220 non-null    object
 1   Caffeine                       220 non-null    object
 2   Roast level                    219 non-null    float64
 3   Roaster                        220 non-null    object
 4   Roaster's country              220 non-null    object
 5   Product weight (grams)         212 non-null    float64
 6   Tasting notes                  201 non-null    object
 7   Rating                         218 non-null    float64
 8   Time rested (days)             181 non-null    float64
 9   Dose (grams)                   220 non-null    float64
 10  Yield (grams)                  220 non-null    float64
 11  Brew ratio                     220 non-null    object
 12  Shot time (seconds)            219 non-null    object
 13  Espresso machine               219 non-null    object
 14  Grinder                        220 non-null    object
 15  Burr set                       74 non-null     object
 16  Grind setting                  189 non-null    object
 17  Water temperature (°C)         170 non-null    float64
 18  Basket specs                   194 non-null    object
 19  Profile                        203 non-null    object
 20  Additional workflow/equipment  178 non-null    object
dtypes: float64(7), object(14)
memory usage: 36.2+ KB

In [8]:
df.nunique()

Origin                            18
Caffeine                           2
Roast level                        7
Roaster                          187
Roaster's country                 28
Product weight (grams)            31
Tasting notes                    201
Rating                            10
Time rested (days)                35
Dose (grams)                      31
Yield (grams)                     42
Brew ratio                        22
Shot time (seconds)               57
Espresso machine                 135
Grinder                          141
Burr set                          16
Grind setting                    139
Water temperature (°C)            21
Basket specs                      95
Profile                           76
Additional workflow/equipment     66
dtype: int64

In [9]:
df = df.drop(columns = ["Burr set", "Profile", "Additional workflow/equipment", "Basket specs"])
df

,Origin,Caffeine,Roast level,Roaster,Roaster's country,Product weight (grams),Tasting notes,Rating,Time rested (days),Dose (grams),Yield (grams),Brew ratio,Shot time (seconds),Espresso machine,Grinder,Grind setting,Water temperature (°C)
0,Colombia,Full caffeine,2.0,Monogram,Canada,300.0,Rum & brown sugar,9.0,7.0,18.0,45.0,1:2.5,30,ECM Synchronika,Monolith MAX Gen 1,1.75,93.8
1,Colombia,Full caffeine,2.0,DAK,Netherlands,1000.0,"Cardamom, vanilla, nuts",10.0,5.0,18.0,45.0,1:2.5,30-35,ECM Synchronika,Monolith MAX Gen 1,NaN,94.4
2,Blend,Full caffeine,4.0,Cat & Cloud,United States,283.0,"Smooth (sorry, my tasting notes are terrible)",8.0,5.0,16.3,33.0,1:2.0,30,DeLonghi ECP 35.31,Baratza Encore ESP,17,NaN
3,Blend,Full caffeine,5.0,Onyx,United States,283.0,"Chocolate, nuts, low acidity",7.0,5.0,18.0,36.0,1:2.0,25-35,La Marzocco Linea Micra,1zpresso J-Ultra,1.35,95.0
4,Blend,Full caffeine,4.0,Black & White,United States,340.0,"Funky, slightly acidic",3.0,14.0,18.0,45.0,1:2.5,25-35,La Marzocco Linea Micra,1Zpresso J-Ultra,1.25,95.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
215,Ethiopia,Full caffeine,3.0,Gracenote Coffee,United States,340.0,"Blueberry cobbler/pie, chocolate",8.0,6.0,16.5,35.5,1:2.2,45,ECM Synchronika II,Zerno Z1,130 nm,94.0
216,Blend,Full caffeine,3.0,Ember and Bean Roasting Co,United States,340.0,NaN,8.0,NaN,19.0,45.0,1:2.4,35,Breville Bambino Plus,Baratza Encore ESP,NaN,NaN
217,Ethiopia,Full caffeine,3.0,Press Coffee,United States,340.0,NaN,8.0,NaN,18.0,36.0,1:2.0,30,Flair Pro 3,DF64,21.5,96.0
218,Brazil,Full caffeine,4.0,Origins Roastery,Montenegro,1000.0,toffee,7.0,8.0,17.0,33.0,1:1.9,28-30,Sanremo You,Eureka Helios,NaN,96.0
219,Colombia,Full caffeine,3.0,Little wolf,United States,NaN,Chocolate cherry,9.0,NaN,20.0,32.0,1:1.6,33,Lelit liz,EM specialita,NaN,95.0

### Deletion of unneccesary columns

At this point of the processing, columns that served as identifiers as well as those that weren't as relevant to the rating were deleted. The next step to the cleaning process involves filling in null values and encoding categorical variables in Tasting notes. The plan is to compare these against the rating. </br>
</br>

**5/23/26** </br>

- Encode following features:
- Caffeine
- Roaster Country
- Tasting Notes

In [11]:
# Encode Caffeine feature via Label Encoding

import sklearn.preprocessing
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['Caffeine'] = le.fit_transform(df['Caffeine'])

print("Caffeine labels mapping:", dict(zip(le.classes_, le.transform(le.classes_))))
df

Caffeine labels mapping: {'Decaf': 0, 'Full caffeine': 1}

,Origin,Caffeine,Roast level,Roaster,Roaster's country,Product weight (grams),Tasting notes,Rating,Time rested (days),Dose (grams),Yield (grams),Brew ratio,Shot time (seconds),Espresso machine,Grinder,Grind setting,Water temperature (°C)
0,Colombia,1,2.0,Monogram,Canada,300.0,Rum & brown sugar,9.0,7.0,18.0,45.0,1:2.5,30,ECM Synchronika,Monolith MAX Gen 1,1.75,93.8
1,Colombia,1,2.0,DAK,Netherlands,1000.0,"Cardamom, vanilla, nuts",10.0,5.0,18.0,45.0,1:2.5,30-35,ECM Synchronika,Monolith MAX Gen 1,NaN,94.4
2,Blend,1,4.0,Cat & Cloud,United States,283.0,"Smooth (sorry, my tasting notes are terrible)",8.0,5.0,16.3,33.0,1:2.0,30,DeLonghi ECP 35.31,Baratza Encore ESP,17,NaN
3,Blend,1,5.0,Onyx,United States,283.0,"Chocolate, nuts, low acidity",7.0,5.0,18.0,36.0,1:2.0,25-35,La Marzocco Linea Micra,1zpresso J-Ultra,1.35,95.0
4,Blend,1,4.0,Black & White,United States,340.0,"Funky, slightly acidic",3.0,14.0,18.0,45.0,1:2.5,25-35,La Marzocco Linea Micra,1Zpresso J-Ultra,1.25,95.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
215,Ethiopia,1,3.0,Gracenote Coffee,United States,340.0,"Blueberry cobbler/pie, chocolate",8.0,6.0,16.5,35.5,1:2.2,45,ECM Synchronika II,Zerno Z1,130 nm,94.0
216,Blend,1,3.0,Ember and Bean Roasting Co,United States,340.0,NaN,8.0,NaN,19.0,45.0,1:2.4,35,Breville Bambino Plus,Baratza Encore ESP,NaN,NaN
217,Ethiopia,1,3.0,Press Coffee,United States,340.0,NaN,8.0,NaN,18.0,36.0,1:2.0,30,Flair Pro 3,DF64,21.5,96.0
218,Brazil,1,4.0,Origins Roastery,Montenegro,1000.0,toffee,7.0,8.0,17.0,33.0,1:1.9,28-30,Sanremo You,Eureka Helios,NaN,96.0
219,Colombia,1,3.0,Little wolf,United States,NaN,Chocolate cherry,9.0,NaN,20.0,32.0,1:1.6,33,Lelit liz,EM specialita,NaN,95.0

In [12]:
# Possibly use one-hot encoding to encode country feature, but how many unique values are there in the Country feature?

# rename roaster's country so that it doesn't include the apostrophe 

df.rename(columns = {"Roaster's country": "Roaster_Country"}, inplace=True)
df

,Origin,Caffeine,Roast level,Roaster,Roaster_Country,Product weight (grams),Tasting notes,Rating,Time rested (days),Dose (grams),Yield (grams),Brew ratio,Shot time (seconds),Espresso machine,Grinder,Grind setting,Water temperature (°C)
0,Colombia,1,2.0,Monogram,Canada,300.0,Rum & brown sugar,9.0,7.0,18.0,45.0,1:2.5,30,ECM Synchronika,Monolith MAX Gen 1,1.75,93.8
1,Colombia,1,2.0,DAK,Netherlands,1000.0,"Cardamom, vanilla, nuts",10.0,5.0,18.0,45.0,1:2.5,30-35,ECM Synchronika,Monolith MAX Gen 1,NaN,94.4
2,Blend,1,4.0,Cat & Cloud,United States,283.0,"Smooth (sorry, my tasting notes are terrible)",8.0,5.0,16.3,33.0,1:2.0,30,DeLonghi ECP 35.31,Baratza Encore ESP,17,NaN
3,Blend,1,5.0,Onyx,United States,283.0,"Chocolate, nuts, low acidity",7.0,5.0,18.0,36.0,1:2.0,25-35,La Marzocco Linea Micra,1zpresso J-Ultra,1.35,95.0
4,Blend,1,4.0,Black & White,United States,340.0,"Funky, slightly acidic",3.0,14.0,18.0,45.0,1:2.5,25-35,La Marzocco Linea Micra,1Zpresso J-Ultra,1.25,95.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
215,Ethiopia,1,3.0,Gracenote Coffee,United States,340.0,"Blueberry cobbler/pie, chocolate",8.0,6.0,16.5,35.5,1:2.2,45,ECM Synchronika II,Zerno Z1,130 nm,94.0
216,Blend,1,3.0,Ember and Bean Roasting Co,United States,340.0,NaN,8.0,NaN,19.0,45.0,1:2.4,35,Breville Bambino Plus,Baratza Encore ESP,NaN,NaN
217,Ethiopia,1,3.0,Press Coffee,United States,340.0,NaN,8.0,NaN,18.0,36.0,1:2.0,30,Flair Pro 3,DF64,21.5,96.0
218,Brazil,1,4.0,Origins Roastery,Montenegro,1000.0,toffee,7.0,8.0,17.0,33.0,1:1.9,28-30,Sanremo You,Eureka Helios,NaN,96.0
219,Colombia,1,3.0,Little wolf,United States,NaN,Chocolate cherry,9.0,NaN,20.0,32.0,1:1.6,33,Lelit liz,EM specialita,NaN,95.0

In [13]:
df['Roaster_Country'].value_counts()

Roaster_Country
United States                     119
Canada                             15
Netherlands                        15
Ukraine                            11
Germany                             9
United Kingdom                      8
Italy                               4
Australia                           4
Switzerland                         3
Denmark                             3
France                              3
Indonesia                           3
Singapore                           2
Japan                               2
American Samoa (United States)      2
Ireland                             2
Norway                              2
India                               2
Israel                              2
Sweden                              1
Spain                               1
Chile                               1
Serbia                              1
New Zealand                         1
Argentina                           1
Belgium                             1
Bermuda (United Kingdom)            1
Montenegro                          1
Name: count, dtype: int64

When thinking about whether or not to label encode or one-hot encode these values, a question that comes to mind is how does each value relate to the question I'm trying to answer. At this point of the analysis, it would be interesting to plot the frequency of each country for the sake of data exploration, but I don't think the column itself would be necessary for prediction purposes. </br>
</br>
For visualization purposes, I think I will extract the `Roaster_Country` as a pandas series, and drop the column from the original dataset.

In [15]:
Roaster_Country = pd.DataFrame(df['Roaster_Country'])
df = df.drop( columns = ['Roaster_Country'])

Roaster_Country

    Roaster_Country
0            Canada
1       Netherlands
2     United States
3     United States
4     United States
..              ...
215   United States
216   United States
217   United States
218      Montenegro
219   United States

[220 rows x 1 columns]

In [16]:
df['Tasting notes'].unique()

array(['Rum & brown sugar', 'Cardamom, vanilla, nuts',
       'Smooth (sorry, my tasting notes are terrible)',
       'Chocolate, nuts, low acidity', 'Funky, slightly acidic',
       'Dark cherry, chocolate finish',
       'Strong, creamy hazelnut flavor, floral finish',
       'Strong berry flavor, pleasant acidity, lingering chocolate finish',
       'Bergamot/lemon, black tea finish',
       'Mixed fruit with mild florality', 'Subtle apple flavor',
       'Slightly floral, slightly acidic',
       'Light white florals, almost sugary sweetness',
       'Apple, a little spice', 'Cocoa, mild, full body',
       'cinnamon (like a ton of cinnamon), chocolate',
       'Chocolate and caramel with nutty and fruity undertones',
       'Hibiscus • Black Currant • Vanilla Custard',
       'Cardamom, Graham, Bakers Spice, Rich and soothing finish',
       'Rich, full bodied', 'Nutty, creamy texture, chocolatey',
       'Bold, rosy tartness', nan,
       'chocolate, semi-sweet toffee, molasses, very smooth',
       'Rich, Earthy, Chocolate with a hint of Caramel, slight fruit note',
       'Very rich, incredibly acidic ', 'Chocolate, brown sugar, rich',
       'Lime, dried cherry, cola', 'Dark chocolate, cherry',
       'Yummy, cherry, chocolate, nut butter',
       'Caramel, full body, low acidity, aromatic, welcome bitterness ',
       'Cocoa, heavy cherry, vanilla, smoke',
       'Rich, syrupy, chocolate and caramel',
       'chocolate, citrus, caramel, mineral (?)',
       'Very fragrant, fruit and nuts',
       'Dark chocolate covered cherries, almond butter, sweet, thick, silky',
       'red fruit, plum, brown sugar',
       'Chocolate notes, small citrus notes.',
       'Chocolate, rich. Modern espresso', 'Good, little bit bitter',
       'Chocolate caramel rich', 'Warm and Earthy',
       'Medium body, fruity, citrus',
       'Rich, buttery, cocoa and walnuts, tart finish',
       'Currants, cherry, caramel', 'Boysenberry, white honey, winey',
       'chocolate, caramel, dark', 'Chocolate, Bright acidity',
       'Almond, gardenia and tangerine', 'Syrupy, Malt, walnut ',
       'chocolate',
       'Red berries, wine sugar, melon rind, lingering, bright, medium-bodied, enveloping.',
       'Creamy caramel, strawberry ( very clean profile )Aftertaste is light, lingering, slightly rough, Body Medium-light ( which is medium).',
       'Black berries, caramel, cinnamon (red orange on the chill) | Aftertaste Light, medium-long, and slightly rough | Body: Medium, smooth.',
       'Cherry pit, red ripe berries (intense sweetness is very strong on cooling - like compote) | Aftertaste: Light, medium-long and slightly rough | Body: Light, smooth.',
       'Cane sugar with lemon, dried fruit compote, some spices (white pepper or something else) | Aftertaste: Smooth, pleasant, lingering | Body: Light but intense',
       'Bright floral, apricot, extremely sweet | Aftertaste: Balanced, not intrusive | Body: Light and very drinkable.',
       'Very mildly acidic with a dark chocolate-y finish',
       'Refreshing, green apple-like acidity, creamy.',
       'Raspberry jam, strawberry lollipops | Aftertaste: Very bright and very rich |Body: Light, clean.',
       'Rich, medium body, caramel head with nutty chocolate body. Very smooth and balanced. ',
       'Insanely fruity, nose of a bowl of Froot Loops, body is acidic, bright, tropical fruit on tongue followed by lavender tea. Unreal. ',
       'Apricot, Peach jam, sweet caramel', 'Pineapple, apple, peach',
       'Clean, floral, black tea', 'Sweet, baked goods',
       'Creamy; chocolate, rich', 'Light caramel, sour cherry',
       'Juicy, bright starting acidity with dark chocolate finish',
       'Luxardo cherry, milk chocolate',
       'Roasty, licorice. Supposed to be medium, tastes like dark. ',
       'Craft chocolate, clean acidity',
       'Fruity and bright, chocolatey, nutty. Tea-like.',
       'blueberries and cream',
       'Smooth, caramel, chocolate, blends well with oatmilk and a little sugar, low acidity',
       'Rich, cocoa nibs, toffee, hazelnut, roasted pecans',
       'chocolate, caramel, sea salt',
       'Rhaspberry, Cherry, Rose Candy, Creamy', 'Rich chocolate',
       'Blackcurrant, milk chocolate, low acidity ',
       "Lemon, something from dried fruits (but I don't understand what it is - maybe dates) | Aftertaste: Medium intensity, not intrusive, sweet | Body: Light, enveloping.",
       'Red currant (very bright), floral. | Aftertaste: High saturation and duration. | Body: Light, clean.',
       'chocolate, molasses, low acidity',
       'Syrupy body, nougat, cashew butter, German chocolate, vanilla',
       'Round and smooth acidity, dark chocolate', 'Charcoal',
       'Black grapes ( I would not call this flavor wine, but rather very lightly fermented grapes ), nougat ( very pronounced ), on cooling it reminds very much of basic loukoum ( well, the one that is white and with some nuts and a lot of starch ).\nAftertaste: Clean, enveloping, rounded.\nBody: Very light and not intrusive (slightly rough on cooling down).',
       'Rich, dark chocolate and caramel, honeycomb and red berries',
       'Pineapple, Funk', 'Chocolate, nutty',
       'Lemon, floral, red berries | Aftertaste: Clean and smooth | Body: Light and rounded.',
       'Raspberry, caramel, chocolate',
       'Floral, Chocolate, Fruity, Honey\nBody: Medium | Finish: Clean',
       'Light body, earthy and nutty, tons of crema ',
       'Dark Chocolate,  Currants, Syrup, Caramel', 'Dark chocolate',
       'Dark Chocolate, Carmel', 'Brown Sugar, Cinnamon, Nutty',
       'Dark Chocolate, Molasses', 'Lemon Candy, Brown Sugar, Chamomile',
       'Sweet; citrus-like acidity', 'Vanilla',
       'Chocolate, Caramel, Creamy', 'Chocolate, hazlenut',
       'Dark chocolate, subtle cherry like', 'Rich caramel and honey ',
       'Maple Syrup, White Chocolate, Dark Rum',
       'Low acidity, complex flavors', 'Milk Chocolate, Caramel, Almond',
       'Chocolate, Nutty',
       'Smoky overtones suggest a dark roast with possible overdevelopment',
       'Honey, almonds & yellow fruits',
       'dark chocolate, hazelnut, caramelized',
       'Subtle, bitter, hazelnut and brown sugar',
       'Rich, thick body, bold caramel flavor, balanced sweetness and bitterness, almost no acidity.',
       'Woody, smoky, walnut, treacle',
       'Juicy, Vibrant, Nectarine Body: Medium | Acidity: Mellow | Finish: Clean, Balanced\n',
       'rich & syrupy body with cherry, dark chocolate with a hint of spices ',
       'Chocolate, strong body',
       'Milk Chocolate, Strawberry, Creamy, Modern',
       'Rich, strong, syrupy body. Chocolatey', 'Rich, chocolatey ',
       'Sweet, fruity, floral', 'Rich, apricot notes, tart finish ',
       'Rich, Chocolate and\nmolasses flavor',
       'Dark chocolate, rich, bold, very low acidity, nutty, smokey',
       'right notes of citrus, tangy-milky mouthfeel, and luscious bass notes of chocolate',
       'Sweet, medium body, milk chocolate and nutty',
       'Plum acidity, fruity almond-y nose, flat cocoa finish.',
       'Pleasant peanut butter and chocolate notes. Smooth acidity, medium, syrupy body.',
       'Rich',
       'Very fresh raspberry, orange peel, mild chocolate, medium body',
       'Cassis, peach, milk chocolate',
       'Toffee, chocolate and cherry. Rich sweetness, a touch of bright acidity, and a velvety body. ',
       'Cinnamon forward, not sweet not spicy, tastes like cinnamon smells, chocolatey and deep',
       'Citrus-like acidity, berries',
       'burnt, burnt chocolate, bitter, very dark',
       'Full-bodied, dark chocolate, malt. low acidity ',
       'Stone Fruits & dark chocolate', 'Chocolate, syrupy ',
       'Papaya, Strawberry, Dragonfruit',
       'thick syrupy dark cherry body, lighter grapefruit finish',
       'Mango, Berrys', 'Mild Acidity, Brown sugar, Pandan after-taste',
       'Syrupy,. chocolate, almond', 'Rich and syrupy body',
       'passionfruit, apricot, peach tea',
       'sweet, dark chocolate, low bitter and acid',
       'Grape jelly, peanut butter, caramel',
       'syrup body, graham cracker, burnt sugar, biscotti',
       'Funky chocolate and wine taste. Very fruit/berry forward',
       'chocolate, tobacco, a bit fruitier taste. very subtle acid. ',
       'Chocolate and wine',
       'Semi-sweet chocolate, light roastiness/smoke',
       '\n\nChocolatey, complex spicy woody, and dark fruit notes. Spicy woody is aromas of a rich wood furniture polish!',
       'Pulled as espresso. 18g in 36g out in 30 seconds. Thin, balanced, medium acidity, mild fruit, underwhelming, over-priced.',
       'Earthy, Walnut, Caramel ', 'Sweet, chocolaty, ripe fruits ',
       'Fruity, Floral, Tea like', 'Delicious', 'Really rich, floral ',
       'Round, malic, peachy',
       'Intense, full body, somewhat spicy / herbal aftertaste',
       'Chocolaty ', 'hazelnut, chocolate',
       'Rich, floral, chocolate, slightly sour',
       'Rich, very floral and earthy',
       'Chocolate caramel with hints of dark fruits', 'Rich, caramel',
       'Cardamom', 'Creamy, Sugarcane, Orange', 'Rich, nutty, chocolate',
       'sweet and fruity, light-medium body',
       'Floral, fruity, blueberry, ',
       'Rich-  good crema, aromatic, caramel with medium acidity',
       'Dark Chocolate, Cherry', 'Pure Watermelon',
       'fruity, almond, gingerbread',
       'Chocolate and hazelnut with notes of fruit. Intense syrupy mouth feel',
       'Milk chocolate and blackberry', 'Earthy, nutty, bold',
       'Bright, chocolatey, caramel notes.', 'Juicy and peachy',
       'Rose, Lytchee, Grapefruit', 'Almond, Aproicot, Vanilla',
       'smoky & chocolatey. I pull my shots ristretto but it still ends up feeling pretty full.',
       'Nutty chocolate',
       'Thinner body; sweet bright apricots; no bitterness',
       'Cherry, Chocolate, Sweet Caramel',
       'dynamic but smooth. clean finish. cocoa nibs and stone fruit.',
       'Berries, milk chocolate ', 'Sweet, floral, juicy, honeysuckle',
       'Fruity, Molasses, Earthy ', 'Blueberry and cool whip',
       'Light smoky, balanced. Slight acidity. Chocolate. (I’m still learning tasting notes and dialing my machine in)',
       'Chocolate, fruity', 'dark chocolate and cherry',
       'Milk chocolate,  hazelnut,  toffee',
       'Black cherry juice, stewed fruit',
       'Blueberry cobbler/pie, chocolate', 'toffee', 'Chocolate cherry '],
      dtype=object)

At this point of the encoding process, I've encountered a challenge in addressing the `Tasting Notes` column. Due to the nature of the responses, there is difficulty in standardizing them in a workable format. Because of that, I started looking at wine flavor datasets and how other people approached columns that contain reviews or multi-worded responses. From that, I saw that someone used the Bag of words (BoW) method. The Bag of Words (BoW) model is a method that converts text into a collection of words, counts how often each word appears in text, and ignores word order and grammar, and focuses only on the frequency. </br>
</br>
**Note** - Don't drop Tasting notes column from the dataframe

**06/1/2026** - **06/02/2026** - </br>

So far, the caffeine column has been encoded, the Roaster Country column has been dropped and made into a separate dataframe for visualization purposes. Now my goal is to use the bag of words method to process the responses for tasting notes and count the word frequencies. I want to be able to visualize how often various tasting notes are inputted as responses. This will help to understand the distribution of words in the dataset.

In [18]:
from collections import Counter

all_notes = []

for row in df['Tasting notes'].dropna():
    notes = [note.strip().lower() for note in row.split(',')]
    all_notes.extend(notes)

freq = Counter(all_notes)

freq_df = pd.DataFrame(
    freq.items(),
    columns=['note', 'count']
).sort_values('count', ascending=False)

In [19]:
freq_df

                                                  note  count
6                                            chocolate     28
36                                                rich     20
59                                             caramel     14
55                                      dark chocolate     12
144                                             floral      9
..                                                 ...    ...
135                                    insanely fruity      1
134  caramel head with nutty chocolate body. very s...      1
132  strawberry lollipops | aftertaste: very bright...      1
131                                      raspberry jam      1
346                                   chocolate cherry      1

[347 rows x 2 columns]

In [20]:
df_caramel = freq_df[freq_df['note'].str.contains('caramel', 'carmel', na=False)]
freq_df = df_caramel['note'].replace('caramel')

C:\Users\Sabrina\AppData\Local\Temp\ipykernel_27616\860389617.py:2: FutureWarning: Series.replace without 'value' and with non-dict-like 'to_replace' is deprecated and will raise in a future version. Explicitly specify the new values instead.
  freq_df = df_caramel['note'].replace('caramel')

So, I didn't use BoW method. Instead, I used a counter that counts the frequency of terms that are separated by commas. However, the problem that I'm finding with this is that it takes entries that contains overlapping notes. I think based on this, it would be better to use Bag of Words.

In [22]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(lowercase=True, stop_words='english')

X = vectorizer.fit_transform(df['Tasting notes'].fillna(''))

word_counts = X.sum(axis=0).A1

freq_df = pd.DataFrame({
    'Word': vectorizer.get_feature_names_out(),
    'Frequency': word_counts

})

freq_df = freq_df.sort_values(
    by='Frequency',
    ascending=False

)

In [23]:
freq_df.head(20)

           Word  Frequency
57    chocolate         84
35         body         34
229        rich         33
46      caramel         29
79         dark         28
5       acidity         25
55       cherry         19
152       light         18
174      medium         18
278       sweet         17
102      floral         14
98       finish         14
113      fruity         13
195       nutty         13
110       fruit         12
281      syrupy         11
273       sugar         11
191       notes         11
39       bright         11
6    aftertaste         11

In [24]:
freq_df = freq_df.drop([191, 155,179,62])

In [25]:
freq_df.head(20)

           Word  Frequency
57    chocolate         84
35         body         34
229        rich         33
46      caramel         29
79         dark         28
5       acidity         25
55       cherry         19
152       light         18
174      medium         18
278       sweet         17
102      floral         14
98       finish         14
113      fruity         13
195       nutty         13
110       fruit         12
281      syrupy         11
273       sugar         11
39       bright         11
6    aftertaste         11
258      smooth         11

In [26]:
freq_df = freq_df.drop([74, 164, 252])

In [27]:
freq_df[freq_df['Word'].str.contains('chocolate', na=False)]

          Word  Frequency
57   chocolate         84
58  chocolatey          8

In [28]:
# create a mapping to unify 'chocolate' terms together

mapping = {
    'chocolate': 'chocolate',
    'chocolatey': 'chocolate'

}

# applying the mapping
freq_df['Word'] = freq_df['Word'].replace(mapping)
freq_df = (
    freq_df
    .groupby('Word', as_index=False)['Frequency']
    .sum()
    .sort_values('Frequency', ascending=False)
)

In [29]:
# searching for words containing fru

freq_df[freq_df['Word'].str.contains('fru', na=False)]

             Word  Frequency
110        fruity         13
107         fruit         12
109        fruits          5
121    grapefruit          2
195  passionfruit          1
82    dragonfruit          1
108      fruitier          1

In [30]:
# create a mapping to unify 'Fruit' terms together

mapping = {
    'fruity': 'fruity',
    'fruit': 'fruity',
    'fruits': 'fruity',
    'fruitier': 'fruity'

}

# applying the mapping
freq_df['Word'] = freq_df['Word'].replace(mapping)
freq_df = (
    freq_df
    .groupby('Word', as_index=False)['Frequency']
    .sum()
    .sort_values('Frequency', ascending=False)
)

In [31]:
freq_df[freq_df['Word'].str.contains('acid', na=False)]

      Word  Frequency
5  acidity         25
4   acidic          5
3     acid          2

In [32]:
mapping = {
    'acidity': 'acidity',
    'acidic': 'acidity',
    'acid': 'acidity',

}

# applying the mapping
freq_df['Word'] = freq_df['Word'].replace(mapping)
freq_df = (
    freq_df
    .groupby('Word', as_index=False)['Frequency']
    .sum()
    .sort_values('Frequency', ascending=False)
)

In [33]:
freq_df.head(20)

           Word  Frequency
55    chocolate         92
33         body         34
217        rich         33
3       acidity         32
105      fruity         31
44      caramel         29
74         dark         28
53       cherry         19
144       light         18
164      medium         18
265       sweet         17
93       finish         14
97       floral         14
183       nutty         13
245      smooth         11
268      syrupy         11
260       sugar         11
37       bright         11
4    aftertaste         11
85       earthy          7

In [34]:
freq_df = freq_df.drop([90])
freq_df.head(20)

           Word  Frequency
55    chocolate         92
33         body         34
217        rich         33
3       acidity         32
105      fruity         31
44      caramel         29
74         dark         28
53       cherry         19
144       light         18
164      medium         18
265       sweet         17
93       finish         14
97       floral         14
183       nutty         13
245      smooth         11
268      syrupy         11
260       sugar         11
37       bright         11
4    aftertaste         11
85       earthy          7

In [35]:
tastingnote_20 = freq_df.head(20)

In [36]:
freq_df['Word'].unique()

array(['chocolate', 'body', 'rich', 'acidity', 'fruity', 'caramel',
       'dark', 'cherry', 'light', 'medium', 'sweet', 'finish', 'floral',
       'nutty', 'smooth', 'syrupy', 'sugar', 'bright', 'aftertaste',
       'earthy', 'red', 'hazelnut', 'berries', 'almond', 'brown',
       'vanilla', 'flavor', 'black', 'cinnamon', 'citrus', 'cocoa',
       'balanced', 'tea', 'toffee', 'strong', 'butter', 'lemon', 'mild',
       'white', 'molasses', 'honey', 'juicy', 'peach', 'apple',
       'strawberry', 'apricot', 'subtle', 'wine', 'smoky', 'nuts',
       'sweetness', 'intense', 'rough', 'spicy', 'bitter', 'bold',
       'lingering', 'syrup', 'little', 'cardamom', 'enveloping', 'orange',
       'blueberry', 'bodied', 'raspberry', 'taste', 'cooling', 'burnt',
       'woody', 'intrusive', 'pleasant', 'walnut', 'bitterness', 'dried',
       'funky', 'graham', 'peanut', 'long', 'ripe', 'sour', 'spice',
       'good', 'pineapple', 'smoke', 'modern', 'plum', 'jam', 'round',
       'spices', 'nibs', 'rounded', 'rum', 'hint', 'semi', 'slight',
       'nose', 'nougat', 'grapes', 'grapefruit', 'rose', 'malt', 'peachy',
       'forward', 'tasting', 'compote', 'complex', 'crema', 'bit',
       'currant', 'chocolaty', 'currants', 'berry', 'tart', 'tastes',
       'candy', 'aromatic', 'espresso', 'stone', 'underwhelming',
       'refreshing', 'rhaspberry', 'profile', 'velvety', 'reminds',
       'understand', 'pure', 'pronounced', 'really', 'undertones', 'pull',
       'pulled', 'unreal', 'vibrant', 'priced', 'whip', 'yellow',
       'pecans', 'peel', 'pepper', 'wood', 'pie', 'winey', 'welcome',
       'pretty', 'pit', 'watermelon', 'warm', 'walnuts', 'polish', 'rind',
       'possible', 'right', 'roast', 'tropical', 'suggest', 'shots',
       'silky', 'small', 'smells', 'tangy', 'tangerine', 'supposed',
       'smokey', 'treacle', 'sugary', 'sugarcane', 'somewhat', 'soothing',
       'sorry', 'stewed', 'starting', 'seconds', 'sea', 'tartness',
       'saturation', 'touch', 'tons', 'ristretto', 'starch', 'roasted',
       'tongue', 'roastiness', 'ton', 'roasty', 'tobacco', 'thinner',
       'rosy', 'texture', 'terrible', 'salt', '18g', 'loukoum',
       'passionfruit', 'dragonfruit', 'cola', 'cool', 'covered',
       'cracker', 'craft', 'cream', 'custard', 'dates', 'deep',
       'delicious', 'dialing', 'don', 'drinkable', 'papaya', 'duration',
       'dynamic', 'ends', 'extremely', 'feeling', 'fermented', 'flat',
       'flavors', 'florality', 'florals', 'followed', 'cobbler', 'chill',
       'cherries', 'charcoal', '36g', 'almonds', 'apricots', 'aproicot',
       'aromas', 'baked', 'bakers', 'basic', 'bass', 'bergamot', 'berrys',
       'biscotti', 'blackberry', 'blackcurrant', 'blends', 'blueberries',
       'bowl', 'boysenberry', 'buttery', 'cane', 'caramelized', 'carmel',
       'cashew', 'cassis', 'chamomile', 'fragrant', 'fresh', 'froot',
       'lollipops', 'lot', '30', 'luscious', 'luxardo', 'lytchee',
       'machine', 'malic', 'mango', 'maple', 'maybe', 'mellow', 'melon',
       'mildly', 'milky', 'mineral', 'mixed', 'mouth', 'mouthfeel',
       'nectarine', 'note', 'nut', 'oatmilk', 'overdevelopment',
       'overtones', 'pandan', 'loops', 'lime', 'funk', 'lightly',
       'furniture', 'gardenia', 'german', 'gingerbread', 'goods', 'grape',
       'green', 'hazlenut', 'head', 'heavy', 'herbal', 'hibiscus', 'high',
       'hints', 'honeycomb', 'honeysuckle', 'incredibly', 'insanely',
       'intensity', 'jelly', 'juice', 'lavender', 'learning', 'licorice',
       'lighter', 'yummy'], dtype=object)

In [37]:
# Using difflib to find tasting notes with similar spellings

from difflib import get_close_matches

freq_lookup = dict(zip(freq_df['Word'], freq_df['Frequency']))

words = freq_df['Word'].tolist()

mapping = {}

for word in words:
    matches = get_close_matches(word, words, n=5, cutoff=0.8)
    
    if len(matches) > 1:
        canonical = max(matches, key=lambda x: freq_lookup[x])

        for match in matches:
            mapping[match] = canonical

In [38]:
mapping["right"] = "right"
mapping["slight"] = "slight"
mapping["bright"] = "bright"
mapping["cherries"] = "cherries"
mapping["bitter"] = "bitter"
mapping["maple"] = "maple"
mapping["starting"] = "starting"
mapping["silky"] = "silky"
mapping["ends"] = "ends"

mapping

{'chocolate': 'chocolate',
 'chocolaty': 'chocolate',
 'caramel': 'caramel',
 'carmel': 'caramel',
 'light': 'light',
 'slight': 'slight',
 'lightly': 'light',
 'lighter': 'light',
 'right': 'right',
 'floral': 'floral',
 'florals': 'floral',
 'florality': 'floral',
 'syrupy': 'syrupy',
 'syrup': 'syrupy',
 'sugar': 'sugar',
 'sugary': 'sugar',
 'bright': 'bright',
 'hazelnut': 'hazelnut',
 'hazlenut': 'hazelnut',
 'berries': 'berries',
 'cherries': 'cherries',
 'almond': 'almond',
 'almonds': 'almond',
 'flavor': 'flavor',
 'flavors': 'flavor',
 'butter': 'butter',
 'buttery': 'butter',
 'bitter': 'bitter',
 'mild': 'mild',
 'mildly': 'mild',
 'juicy': 'juicy',
 'juice': 'juicy',
 'peach': 'peach',
 'peachy': 'peach',
 'apple': 'apple',
 'maple': 'maple',
 'apricot': 'apricot',
 'aproicot': 'apricot',
 'apricots': 'apricot',
 'wine': 'wine',
 'winey': 'wine',
 'smoky': 'smoky',
 'smokey': 'smoky',
 'smoke': 'smoky',
 'nuts': 'nuts',
 'nut': 'nuts',
 'spicy': 'spicy',
 'spice': 'spices',
 'blueberry': 'blueberry',
 'blueberries': 'blueberry',
 'raspberry': 'raspberry',
 'rhaspberry': 'raspberry',
 'taste': 'taste',
 'tastes': 'taste',
 'woody': 'woody',
 'wood': 'woody',
 'walnut': 'walnut',
 'walnuts': 'walnut',
 'funky': 'funky',
 'funk': 'funky',
 'spices': 'spices',
 'good': 'good',
 'goods': 'good',
 'round': 'rounded',
 'rounded': 'rounded',
 'hint': 'hint',
 'hints': 'hint',
 'grapes': 'grapes',
 'grape': 'grapes',
 'tasting': 'tasting',
 'starting': 'starting',
 'crema': 'crema',
 'cream': 'crema',
 'currant': 'currants',
 'currants': 'currants',
 'berry': 'berry',
 'berrys': 'berry',
 'pull': 'pulled',
 'pulled': 'pulled',
 'yellow': 'mellow',
 'mellow': 'mellow',
 'roast': 'roasty',
 'roasty': 'rosy',
 'roasted': 'roasted',
 'silky': 'silky',
 'milky': 'milky',
 'tons': 'ton',
 'ton': 'ton',
 'rosy': 'rosy',
 'ends': 'ends',
 'blends': 'blends'}

In [39]:
freq_df['Word'] = freq_df['Word'].replace(mapping)

freq_df = (
    freq_df
    .groupby('Word', as_index=False)['Frequency']
    .sum()
    .sort_values('Frequency', ascending=False)
)

In [40]:
tastingnote_20 = freq_df.head(20)
tastingnote_20

           Word  Frequency
48    chocolate         94
28         body         34
190        rich         33
3       acidity         32
91       fruity         31
38      caramel         30
64         dark         28
124       light         20
46       cherry         19
142      medium         18
232       sweet         17
85       floral         16
82       finish         14
234      syrupy         14
159       nutty         13
228       sugar         12
4    aftertaste         11
214      smooth         11
32       bright         11
102    hazelnut          8

Lol what just happened. Okay, so I worked with the raw tasting note data. At first, I wanted to employ the BoW method, but ended up using a counter, which takes all inputs separated by commas and separates them into frequencies. This wasn't very effective for my purposes because different notes would overlap in a single entry, or a single entry would consist of a whole sentence. In order to properly visualize, I need single-word descriptors. Because of this, I attempted to use the BoW method again, processing the column responses so that it would return single terms and how many times it would appear in the data entries. **It should be noted that only the first steps towards BoW were used: Tokenization, Preprocessing, and Counting.** Tokenization breaks the text into individual words (tokens). Preprocessing converts all the text into lowercase, ignoring punctuation. Counting builds a vocabulary of all the unique words and counts the frequency. What was returned was a new data frame that features each word and its frequency. </br>
</br>
At this point, there were plenty of unnecessary words, and I started to manually delete the entries that I intially deemed unrelated to tasting notes. That process looked like going back and forth between examining the inputs via .unique(), and dropping entries based on their index. I would keep checking the top 20 terms, and if there was a term that looked odd, I would go through the process of dropping again. The problem I found with this was how tedious the work became in addition to acknowleding the sense of bias involved in deciding what terms to keep or let go of. Because of this, I started using the get_close_matches from the difflib module to identify the terms that were similar in spelling. This helped in identifying terms whose frequencies I can merge together via mapping. Doing this simplified the tasting notes immensely, preparing it for visualization. </br>

---

In [42]:
df

,Origin,Caffeine,Roast level,Roaster,Product weight (grams),Tasting notes,Rating,Time rested (days),Dose (grams),Yield (grams),Brew ratio,Shot time (seconds),Espresso machine,Grinder,Grind setting,Water temperature (°C)
0,Colombia,1,2.0,Monogram,300.0,Rum & brown sugar,9.0,7.0,18.0,45.0,1:2.5,30,ECM Synchronika,Monolith MAX Gen 1,1.75,93.8
1,Colombia,1,2.0,DAK,1000.0,"Cardamom, vanilla, nuts",10.0,5.0,18.0,45.0,1:2.5,30-35,ECM Synchronika,Monolith MAX Gen 1,NaN,94.4
2,Blend,1,4.0,Cat & Cloud,283.0,"Smooth (sorry, my tasting notes are terrible)",8.0,5.0,16.3,33.0,1:2.0,30,DeLonghi ECP 35.31,Baratza Encore ESP,17,NaN
3,Blend,1,5.0,Onyx,283.0,"Chocolate, nuts, low acidity",7.0,5.0,18.0,36.0,1:2.0,25-35,La Marzocco Linea Micra,1zpresso J-Ultra,1.35,95.0
4,Blend,1,4.0,Black & White,340.0,"Funky, slightly acidic",3.0,14.0,18.0,45.0,1:2.5,25-35,La Marzocco Linea Micra,1Zpresso J-Ultra,1.25,95.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
215,Ethiopia,1,3.0,Gracenote Coffee,340.0,"Blueberry cobbler/pie, chocolate",8.0,6.0,16.5,35.5,1:2.2,45,ECM Synchronika II,Zerno Z1,130 nm,94.0
216,Blend,1,3.0,Ember and Bean Roasting Co,340.0,NaN,8.0,NaN,19.0,45.0,1:2.4,35,Breville Bambino Plus,Baratza Encore ESP,NaN,NaN
217,Ethiopia,1,3.0,Press Coffee,340.0,NaN,8.0,NaN,18.0,36.0,1:2.0,30,Flair Pro 3,DF64,21.5,96.0
218,Brazil,1,4.0,Origins Roastery,1000.0,toffee,7.0,8.0,17.0,33.0,1:1.9,28-30,Sanremo You,Eureka Helios,NaN,96.0
219,Colombia,1,3.0,Little wolf,NaN,Chocolate cherry,9.0,NaN,20.0,32.0,1:1.6,33,Lelit liz,EM specialita,NaN,95.0

As of now, I extracted the tasting notes column and employed the preprocessing steps from the BoW method to identify the top 20 notes based on frequencies. This will be used for visualization purposes. Another relationship I would like to look into is between notes and ratings. To do this, I will extract the tasting notes and ratings columns, split the notes based on delimiters, and explode it.

In [44]:
df['Tasting notes']

0                                  Rum & brown sugar
1                            Cardamom, vanilla, nuts
2      Smooth (sorry, my tasting notes are terrible)
3                       Chocolate, nuts, low acidity
4                             Funky, slightly acidic
                           ...
215                 Blueberry cobbler/pie, chocolate
216                                              NaN
217                                              NaN
218                                           toffee
219                                Chocolate cherry
Name: Tasting notes, Length: 220, dtype: object

In [45]:
import re

#standardizing delimiter format by replacing with ','
tn_og = pd.DataFrame(df.copy())
tn_og['Tasting notes'] = tn_og['Tasting notes'].str.replace(r'[&/.]', ',', regex=True)

In [46]:
tn_og['Tasting notes'] = tn_og['Tasting notes'].replace({'Smooth (sorry, my tasting notes are terrible)': 'Smooth'})
tn_og

,Origin,Caffeine,Roast level,Roaster,Product weight (grams),Tasting notes,Rating,Time rested (days),Dose (grams),Yield (grams),Brew ratio,Shot time (seconds),Espresso machine,Grinder,Grind setting,Water temperature (°C)
0,Colombia,1,2.0,Monogram,300.0,"Rum , brown sugar",9.0,7.0,18.0,45.0,1:2.5,30,ECM Synchronika,Monolith MAX Gen 1,1.75,93.8
1,Colombia,1,2.0,DAK,1000.0,"Cardamom, vanilla, nuts",10.0,5.0,18.0,45.0,1:2.5,30-35,ECM Synchronika,Monolith MAX Gen 1,NaN,94.4
2,Blend,1,4.0,Cat & Cloud,283.0,Smooth,8.0,5.0,16.3,33.0,1:2.0,30,DeLonghi ECP 35.31,Baratza Encore ESP,17,NaN
3,Blend,1,5.0,Onyx,283.0,"Chocolate, nuts, low acidity",7.0,5.0,18.0,36.0,1:2.0,25-35,La Marzocco Linea Micra,1zpresso J-Ultra,1.35,95.0
4,Blend,1,4.0,Black & White,340.0,"Funky, slightly acidic",3.0,14.0,18.0,45.0,1:2.5,25-35,La Marzocco Linea Micra,1Zpresso J-Ultra,1.25,95.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
215,Ethiopia,1,3.0,Gracenote Coffee,340.0,"Blueberry cobbler,pie, chocolate",8.0,6.0,16.5,35.5,1:2.2,45,ECM Synchronika II,Zerno Z1,130 nm,94.0
216,Blend,1,3.0,Ember and Bean Roasting Co,340.0,NaN,8.0,NaN,19.0,45.0,1:2.4,35,Breville Bambino Plus,Baratza Encore ESP,NaN,NaN
217,Ethiopia,1,3.0,Press Coffee,340.0,NaN,8.0,NaN,18.0,36.0,1:2.0,30,Flair Pro 3,DF64,21.5,96.0
218,Brazil,1,4.0,Origins Roastery,1000.0,toffee,7.0,8.0,17.0,33.0,1:1.9,28-30,Sanremo You,Eureka Helios,NaN,96.0
219,Colombia,1,3.0,Little wolf,NaN,Chocolate cherry,9.0,NaN,20.0,32.0,1:1.6,33,Lelit liz,EM specialita,NaN,95.0

In [47]:
tn_og['Tasting notes'] = tn_og['Tasting notes'].str.split(",")

tn_exploded = tn_og.explode('Tasting notes')
tn_exploded['Tasting notes'] = tn_exploded['Tasting notes'].str.strip()

In [48]:
tn_exploded = pd.DataFrame(tn_exploded[['Tasting notes', 'Rating']])
tn_exploded

        Tasting notes  Rating
0                 Rum     9.0
0         brown sugar     9.0
1            Cardamom    10.0
1             vanilla    10.0
1                nuts    10.0
..                ...     ...
215         chocolate     8.0
216               NaN     8.0
217               NaN     8.0
218            toffee     7.0
219  Chocolate cherry     9.0

[612 rows x 2 columns]

In [49]:
df = pd.DataFrame(tn_og)
df

,Origin,Caffeine,Roast level,Roaster,Product weight (grams),Tasting notes,Rating,Time rested (days),Dose (grams),Yield (grams),Brew ratio,Shot time (seconds),Espresso machine,Grinder,Grind setting,Water temperature (°C)
0,Colombia,1,2.0,Monogram,300.0,"[Rum , brown sugar]",9.0,7.0,18.0,45.0,1:2.5,30,ECM Synchronika,Monolith MAX Gen 1,1.75,93.8
1,Colombia,1,2.0,DAK,1000.0,"[Cardamom, vanilla, nuts]",10.0,5.0,18.0,45.0,1:2.5,30-35,ECM Synchronika,Monolith MAX Gen 1,NaN,94.4
2,Blend,1,4.0,Cat & Cloud,283.0,[Smooth],8.0,5.0,16.3,33.0,1:2.0,30,DeLonghi ECP 35.31,Baratza Encore ESP,17,NaN
3,Blend,1,5.0,Onyx,283.0,"[Chocolate, nuts, low acidity]",7.0,5.0,18.0,36.0,1:2.0,25-35,La Marzocco Linea Micra,1zpresso J-Ultra,1.35,95.0
4,Blend,1,4.0,Black & White,340.0,"[Funky, slightly acidic]",3.0,14.0,18.0,45.0,1:2.5,25-35,La Marzocco Linea Micra,1Zpresso J-Ultra,1.25,95.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
215,Ethiopia,1,3.0,Gracenote Coffee,340.0,"[Blueberry cobbler, pie, chocolate]",8.0,6.0,16.5,35.5,1:2.2,45,ECM Synchronika II,Zerno Z1,130 nm,94.0
216,Blend,1,3.0,Ember and Bean Roasting Co,340.0,NaN,8.0,NaN,19.0,45.0,1:2.4,35,Breville Bambino Plus,Baratza Encore ESP,NaN,NaN
217,Ethiopia,1,3.0,Press Coffee,340.0,NaN,8.0,NaN,18.0,36.0,1:2.0,30,Flair Pro 3,DF64,21.5,96.0
218,Brazil,1,4.0,Origins Roastery,1000.0,[toffee],7.0,8.0,17.0,33.0,1:1.9,28-30,Sanremo You,Eureka Helios,NaN,96.0
219,Colombia,1,3.0,Little wolf,NaN,[Chocolate cherry ],9.0,NaN,20.0,32.0,1:1.6,33,Lelit liz,EM specialita,NaN,95.0

---

**6/15/26** - </br>

At this point of the cleaning process, there are categorical features such as the machine used, grinder, brew ratio, and shot time that can be helpful in identifying what combinations result in a high bean rating. But, what is actually relevant? Can I get away with deleting the grinder and the grind size?? Or would that be good information to have?

In [97]:
df.to_csv('espresso_brew_v2.csv', index=False)
Roaster_Country.to_csv('roaster_country.csv', index=False)
tastingnote_20.to_csv('top20_notes.csv', index=False)
tn_exploded.to_csv('tn_exploded.csv', index=False)

### DataFrames created in this notebook

- df = cleaned version of raw data
- Roaster_Country = Roaster country of origin -> visualize frequency of countries
- freq_df = contains all tasting notes
- tastingnote_20 = top 20 tasting notes based on frequency -> visualize top 20 tasting notes
- tn_exploded = tasting notes separated along with rating -> visualize relationship between tasting notes and rating. Want to see what notes are correlated with higher ratings

### Appendix

- **Origin** - Country of origin or blend
- **Caffeine** - Caffeine or Decaf
- **Roast level** - Level of roast on a scale from 1-7 (Assumed: Cinnamon, Light, City/Medium, Full City, Dark, French, Italian)
- **Roaster** - Who roasted the beans
- **Roaster's country** - Country where roaster was located
- **Product weight (grams)** - The weight of the product in grams
- **Tasting notes** - Coffee flavor profile (personal)
- **Rating** - Score given to the brew
- **Time rested (days)** - Time given in days for freshly roasted beans to degas (this allows the beans to reach peak flavor )
- **Dose (grams)** - Dosage pulled for extraction
- **Yield (grams)** - How much espresso was extracted
- **Brew ratio** - The proportion of coffee to water
- **Shot time (seconds)** - How long it took to pull the shot in seconds
- **Espresso machine** - Brand and model of the espresso machine used
- **Grinder** - Brand and model of grinder used
- **Grind setting** - Setting used on the grinder
- **Water temperature (°C)** - Temperature of water used to pull the shot in (°C)
- **Basket specs** - Refers to the espresso basket used